config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'locations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :locations, only: [:show] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :edit, :update, :destroy] #do
  #   resources :combinations, only: [:new, :create]
  # end
  get '/bookings/:id/choose_beds', to: 'bookings#choose_beds', as: 'choose_beds'
  patch '/bookings/:id/add_beds', to: 'bookings#add_beds', as: 'add_beds'
  patch '/bookings/:id/decline', to: 'bookings#decline', as: 'decline'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
  belongs_to :location
  has_many :combinations, dependent: :delete_all
  has_many :bookings, through: :combinations

  validates :location, presence: true
  validates :size, presence: true, numericality: { greater_than: 0 }
  validates :name, presence: true, uniqueness: { scope: :location }
end

app/models/booking.rb
class Booking < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :user
  belongs_to :location
  has_many :combinations, dependent: :delete_all
  has_many :beds, through: :combinations

  validates_with MyValidator
  validates :place, presence: true, numericality: { greater_than: 0 }
  validates :status, inclusion: { in: %w[pending accepted declined] }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :location, presence: true

  def mark_as(state)
    if %w[accepted declined pending].include?(state)
      self.status = state
    end
  end
end

app/models/combination.rb
class Combination < ApplicationRecord
  belongs_to :bed
  belongs_to :booking

  validates :booking, presence: true
  validates :bed, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :beds, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user

  def no_of_places
    total = 0
    beds = self.beds
    beds.each do |bed|
      total += bed.size
    end
    total
  end
end

app/models/my_validator.rb
class MyValidator < ActiveModel::Validator
  def validate(record)
    unless record.end_date.to_time.to_i > record.start_date.to_time.to_i
      record.errors[:end_date] << "Impossible de partir avant d'être arriver"
    end
    unless record.place <= record.location.no_of_places
      record.errors[:place] << "Il n'y a pas autant de place ici"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :locations
  has_many :bookings
  has_many :beds, through: :locations
  has_many :bookings_as_host, through: :locations, source: :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "Attention tu n'as pas les autorisation pour faire ca!"
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_location, only: %i[new create]
  before_action :set_booking, except: %i[index new create]
    # only: %i[edit update choose_beds add_beds destroy deny]
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @places = @location.no_of_places
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = current_user.bookings.build(booking_params.merge(location: @location))
    authorize @booking
    if @booking.save
      send_new_booking_email(@booking)
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
    @location = @booking.location
  end

  def update
    if @booking.update(booking_params)
      unless current_user.admin
        @booking.mark_as("pending")
        @booking.save!
        Combination.where(booking: @booking).destroy_all
      end
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def choose_beds
    # faire de ca une modal
  end

  def add_beds
    # pourquoi est ce que d'habitude je dois passer par une methode privé alors que la ca marche seul, ou comment faire pour passer par une méthode privée?
    # Get the bed instances from the ids in the params
    beds = params[:booking][:bed_ids][:ids]
    beds.each do |id|
      # For each bed create a combination with the booking
      Combination.create!(
        bed: Bed.find(id),
        booking: @booking
      )
    end
    # if all combinations have been saved accept status of booking
    @booking.mark_as("accepted")
    if @booking.save
      # mettre un pop-up pour dire que ca a été successfull
      redirect_to bookings_path
    else
      raise
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def decline
    @booking.mark_as("declined")
    if @booking.save
      @booking.combinations.destroy_all
      render :edit
    end
  end

  private

  def send_new_booking_email(booking)
    @admins = User.where(admin: "true")
    BookingMailer.newBooking(booking, @admins).deliver_now
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def set_location
    @location = Location.find(params[:location_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :place, :message, :bed_ids)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @locations = policy_scope(Location)
  end

  def show
    @location = Location.find(params[:id])
    authorize @location
    events = @location.bookings.where(status: "accepted")
    @upcoming_bookings = events.where('start_date >= ?', Date.current).order(start_date: :asc).first(5)
    @events = events.map do |booking|
      {
        title: booking.user.first_name,
        start: booking.start_date,
        end: booking.end_date,
        allDay: true
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    # @reservations = Reservation.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_admin_card.html.erb
<div class="admin-card">
  <div class="picture-area" style="background-image: linear-gradient(180.34deg, rgba(255, 255, 255, 0) 0.29%, rgba(57, 112, 147, 0.57) 41.71%), url(<%= image_url('gab.jpg') %>); background-size: cover">
    <div class="pic-text">
      <% if booking.user == current_user && current_user.admin %>
        <p class="name">MOI</p>
      <% else %>
        <p class="name"><%= booking.user.first_name.upcase %></p>
      <% end %>
    </div>
  </div> <!-- end picture area -->
  <div class="card-text">
    <div class="admin-card-content">
      <p><%= booking.place > 1 ? "#{booking.place} lits" : "#{booking.place} lit" %></p>
      <div class="dates">
        <div class="date">
          <p>Du:</p>
          <p id="jour"><%= I18n.l(booking.start_date, format: "%a %d %B", locale: :'fr')%></p>
        </div>
        <div class="date">
          <p>Au:</p>
          <p id="jour"><%= I18n.l(booking.end_date, format: "%a %d %B", locale: :'fr') %></p>
        </div>
      </div>
    </div> <!-- end admin-card-content -->
    <div class="btns-admin-card">
      <% if policy(booking).choose_beds? %>
        <div class="btn-card btn-accept">
          <%= link_to "Accepter", choose_beds_path(booking) %>
        </div>
      <% end %>
      <% if policy(booking).decline? %>
        <div class="btn-card btn-decline">
          <%= link_to "Refuser", decline_path(booking), method: :patch %>
        </div>
      <% end %>
    </div> <!-- end btns-admin-card -->
    <div class="message-admin-card">
      <% if booking.status == "accepted" %>
        <div class="lits">
          <% booking.beds.each do |bed| %>
            <div class="lit">
              <%= bed.name %>
            </div> <!-- end lit -->
          <% end %>
        </div> <!-- end lits -->
      <% else %>
        <% if booking.message == ""%>
          <p>Il n'y a pas de message</p>
        <% else %>
          <p><%= booking.message %></p>
        <% end %>
      <% end %>
    </div> <!-- end message-admin-card -->
  </div> <!-- end card-text -->
</div>

app/views/bookings/_admin_index.html.erb
<%= content_for(:navbar_title, "Les Demandes") %>
<% if !@bookings.where(status: "pending").empty? %>
  <h3>En Attente</h3>
  <div class="bookings-scroll">
    <% @bookings.each do |booking| %>
      <% if booking.status == "pending" %>
          <%= render "admin_card", booking: booking %>
      <% end %>
    <% end %>
  </div>
<% end %>
<% if !@bookings.where(status: "accepted").empty? %>
  <h3>Accepter</h3>
  <div class="bookings-scroll">
    <% @bookings.each do |booking| %>
      <% if booking.status == "accepted" %>
          <%= render "admin_card", booking: booking %>
      <% end %>
    <% end %>
  </div>
<% end %>
<% if !@bookings.where(status: "declined").empty? %>
  <h3>Refuser</h3>
  <div class="bookings-scroll">
    <% @bookings.each do |booking| %>
      <% if booking.status == "declined" %>
        <%= render "admin_card", booking: booking %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8">
      <div class="form-post">
        <h1>Ta demande</h1>
        <%= simple_form_for [setters[:location], setters[:booking]] do |f| %>
          <!-- <div class='input-group date' id='flatpickr'> -->
            <%= f.input :start_date,
                        as: :string,
                        required: false %>
          <!-- </div> -->
          <%= f.input :end_date,
                      as: :string,
                      required: false %>
          <% location = setters[:location] ? setters[:location] : setters[:booking].location %>
          <%= f.input :place,
                      collection: 1..location.no_of_places,
                      required: false,
                      default: 1 %> <!-- make this a slider -->
          <%= f.input :message,
                      label: "Message (optionnel)",
                      placeholder: "Ici vont tes mots doux" %>
          <%= f.submit setters[:prompt], class: "home-btn btn" %>
        <% end %>
        <% if setters[:location] %>
          <%= link_to "Annuler", location_path(setters[:location]) %>
        <% else %>
          <%= link_to "Annuler", bookings_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_user_card.html.erb
<div class="user-card">
  <div class="picture-area" style="background-image: linear-gradient(rgba(0, 0, 0, 0.44), rgba(0, 0, 0, 0.44)), url(<%= image_url('photo-appart.jpg') %>); background-size: cover">
    <div class="pic-text">
      <p>
        <%if booking.status == "accepted" %>
          Accepter
        <% elsif booking.status == "pending" %>
          En Attente
        <% else %>
          Refuser
        <% end %>
      </p>
    </div>
  </div>
  <div class="user-card-text">
    <div class="dates">
      <div class="date">
        <p>Du: <%= booking.start_date.strftime('%a %d %b') %></p>
      </div> <!-- end date -->
      <div class="date">
        <p>Au: <%= booking.end_date.strftime('%a %d %b') %></p>
      </div> <!-- end date -->
    </div> <!-- end dates -->
    <div class="lits-user-card">
      <% if booking.status == "accepted" %>
        <div class="message-user-accepter" id="dropdownlits" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <p>Tes lits</p>
          <i class="fas fa-angle-down"></i>
        </div>
        <div class="dropdown-lits dropdown-menu" aria-labelledby="dropdownlits">
          <% booking.beds.each do |bed| %>
            <div class="lit">
              <%= bed.name %>
            </div> <!-- end lit -->
          <% end %>
        </div> <!-- end dropdown-lits dropdown-menu -->
      <% else %>
        <p class="message-user">Tu n'as pas encore de lit</p>
      <% end %>
    </div> <!-- end lits-user-card -->
    <div class="btn-card btn-modify">
      <%= link_to "Modifier", edit_booking_path(booking) %>
    </div><!-- end btn-card btn-modify -->
  </div><!-- end user-card-text -->
</div><!-- end user-card -->

app/views/bookings/_user_index.html.erb
<%= content_for(:navbar_title, "Mes Demandes") %>
<% if !@bookings.where(status: "declined").empty? %>
  <h3>Refuser</h3>
  <% @bookings.each do |booking| %>
    <% if booking.status == "declined" %>
      <%= render "user_card", booking: booking %>
    <% end %>
  <% end %>
<% end %>
<% if !@bookings.where(status: "pending").empty? %>
  <h3>En Attente</h3>
  <% @bookings.each do |booking| %>
    <% if booking.status == "pending" %>
        <%= render "user_card", booking: booking %>
    <% end %>
  <% end %>
<% end %>
<% if !@bookings.where(status: "accepted").empty? %>
  <h3>Accepter</h3>
  <% @bookings.each do |booking| %>
    <% if booking.status == "accepted" %>
        <%= render "user_card", booking: booking %>
    <% end %>
  <% end %>
<% end %>

app/views/bookings/choose_beds.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8">
      <div class="form-post">
        <h2>Attribution des lits</h2>
        <p data="<%= @booking.place %>" id="bed-counter"></p>
          <form class="simple_form add_beds" id="add_beds_<%= @booking.id %>" novalidate="novalidate" action="/bookings/<%= @booking.id %>/add_beds" accept-charset="UTF-8" method="post">
            <input type="hidden" name="_method" value="patch">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="bed-choices">
              <% @booking.location.beds.each do |bed| %>
                <input type="checkbox" class="hidden" value="<%= bed.id %>" name="booking[bed_ids]ids[]" id="booking_bed_ids_<%= bed.id %>">
                <label for="booking_bed_ids_<%= bed.id %>" class="bed-choice" bed_size="<%= bed.size %>">
                  <%= bed.name %>
                </label>
              <% end %>
            </div>
            <input value="Attribuer" type="submit" class="btn home-btn" data-disable-with="Save">
          </form>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<%= render "form", setters: {booking: @booking, prompt: "Modifier"} %>
<%= link_to "Supprimer", booking_path(@booking), method: :delete %>

app/views/bookings/index.html.erb
<% if current_user.admin? %>
  <%= render "admin_index" %>
<% else %>
  <%= render "user_index" %>
<% end %>

app/views/bookings/new.html.erb
<%= render "form", setters: {location: @location, booking: @booking,prompt: "Envoyer"} %>

app/views/bookings/show.html.erb
<h4>Et la tu vois les details d'une reervation en particulier</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <title>Point de Chute</title>
    <%= favicon_link_tag 'tab-icon.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- PWA optimisation set up -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/locations/index.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div class="banner">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xs-12 col-sm-8">
        <div class="home-title text-center">
          <h1>Tu veux dormir chez nous?</h1>
          <h3>Choisis où:</h3>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-xs-12 col-sm-8">
        <div class="home-buttons">
          <% @locations.each do |location| %>
            <%= link_to "#{location.name}", location_path(location), class: "btn home-btn"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<%= content_for(:navbar_title, "#{@location.name}") %>
<%= image_tag('calendar_banner.jpg', id: "my-special-banner") %>
<div class="my-container">
  <div class="calendar-container">
    <div id="calendar" class="text-center" data-events="<%= @events.to_json %>"></div>
  </div>
  <!-- pour choisir la taille du calendrier : mettre le calendrier dans une div et donner les dimension que je veux a cette div -->
  <div class="under-calendar">
    <% if current_user.admin %>
      <p>Prochaines arrivées:<p>
      <div class="next-guest-display">
        <% @upcoming_bookings.each do |upcoming| %>
          <div class="avatar-date">
            <%= image_tag "gab.jpg", class: "avatar" %>
            <p><%= upcoming.start_date.strftime("Le %d/%m") %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= link_to(new_location_booking_path(@location)) do %>
  <%= image_tag "add-btn-perso.svg", class: "btn-add" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="my-navbar navbar navbar-expand-sm <%= yield(:navbar_class) %>">
  <% if user_signed_in? %>
      <%= image_tag "menu_burger_perso.svg", class: "menu-burger dropdown-toggle", id: "navMenu", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="my-dropdown dropdown-menu" aria-labelledby="navMenu"> <!-- start of everything that goes into the dropdown -->
        <div class="nav-profile-info">
          <%= image_tag "gab.jpg", class: "avatar nav-avatar" %>
          <div class="nav-profile-content">
            <p><strong><%= current_user.first_name.capitalize %></strong></p>
            <p><%= current_user.email %></p>
          </div>
        </div>
        <div class="nav-demandes dropdown-item">
          <% if current_user.admin %>
            <%= link_to "Les Demandes", bookings_path %>
            <span class="badge badge-primary badge-pill"><%= current_user.bookings_as_host.where(status:"pending").count %></span>
          <% else %>
            <%= link_to "Mes Demandes", bookings_path %>
          <% end %>
        </div>
        <%= link_to "#{Location.find(1).name}", location_path(1), class: "dropdown-item" %>
        <%= link_to "#{Location.find(2).name}", location_path(2), class: "dropdown-item" %>
        <%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item disconnect" %>
      </div> <!-- end of everything that goes into the dropdown -->
  <% else %>
      <%= link_to "Se Connecter", new_user_session_path, class: "nav-link" %>
  <% end %>
  <% if yield(:navbar_title) %>
     <p class="nav-location-name"><%= yield(:navbar_title) %></p>
  <% end %>
</div>